[general]
import = [
    "~/.config/alacritty/themes/rose-pine.toml"
]

[env]
TERM = 'xterm-256color'

[window]
padding = { x = 6, y = 6 }
decorations = 'None'
opacity = 0.95

[font]
normal = { family = 'IosevkaTerm Nerd Font', style = 'Regular' }
bold = { family = 'IosevkaTerm Nerd Font', style = 'Bold' }
italic = { family = 'IosevkaTerm Nerd Font', style = 'Italic' }
size = 11

[cursor]
style = { blinking = 'Always' }
