local map = require('utils').map

map('i', '<C-H>', '<C-W>', 'Borrar palabras completas en insert')
map('n', 'sh', '<C-w>H', 'Mueve split hacia la izquierda')
map('n', 'sj', '<C-w>J', 'Mueve split hacia abajo')
map('n', 'sk', '<C-w>K', 'Mueve split hacia arriba')
map('n', 'sl', '<C-w>L', 'Mueve split hacia la derecha')
map('n', '<Up>', '<cmd>resize +2<CR>', 'Aumenta altura de split')
map('n', '<Right>', '<cmd>vertical resize -2<CR>', 'Aumenta ancho de split')
map('n', '<Left>', '<cmd>vertical resize +2<CR>', 'Disminuye ancho de split')
map('n', '<Down>', '<cmd>resize -2<CR>', 'Disminuye altura de split')
map('n', '<C-d>', '<C-d>zz', 'Navega hacia abajo en el buffer')
map('n', '<C-u>', '<C-u>zz', 'Navega hacia arriba en el buffer')
map('n', 'n', 'nzzzv', 'Navega al siguiente resultado de busqueda')
map('n', 'N', 'Nzzzv', 'Navega al anterior resultado de busqueda')
map('n', '<leader>qn', '<cmd>cn<CR>', 'Navega al siguiente elemento del quickfix')
map('n', '<leader>qp', '<cmd>cp<CR>', 'Navega al anterior elemento del quickfix')
